version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    container_name: meu-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  strapi:
    build:
      context: ./back
    ports:
      - "1337:1337"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    command: yarn start  # Comando de inicialização do Strapi usando Yarn
    volumes:
        - strapi-app:/usr/src/api
  nextjs:
      build:
        context: ./front # Substitua pelo caminho para o seu código-fonte do Next.js
        dockerfile: Dockerfile
      container_name: meu-nextjs
      ports:
        - "3000:3000"
      depends_on:
        - strapi

volumes:
    postgres-data:
    strapi-app: