version: '3.1'
services:
  # postgres:
  #   image: postgres:latest
  #   restart: always
  #   env_file: .env
  #   container_name: meu-postgres
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  strapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
  nextjs:
      build:
        context: ./front # Substitua pelo caminho para o seu código-fonte do Next.js
        dockerfile: Dockerfile
      container_name: meu-nextjs
      ports:
        - "3000:3000"
      depends_on:
        - strapi

volumes:
    # postgres-data:
    strapi-app: