version: '3.1'

services:
  banco:
    image: postgres:latest
    container_name: meu-postgres-container
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data # Mapeia o diretório de dados do PostgreSQL
    networks:
      - local_network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_BROWSER=on
      - MINIO_OPTS=CORS_ALLOWED_HEADERS=x-requested-with,authorization,Content-Type,Accept,Origin
      - MINIO_OPTS=CORS_ALLOWED_METHODS=GET,PUT,POST,DELETE
      - MINIO_OPTS=CORS_ALLOWED_ORIGINS=http://localhost:1337
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    networks:
      - local_network

  strapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - banco
      - minio
    volumes:
      - ./data/strapi:/srv/app
    networks:
      - local_network
    command: start --path /cartilha/strapi


  nextjs:
    build:
      context: ./front # Substitua pelo caminho para o seu código-fonte do Next.js
      dockerfile: Dockerfile
    container_name: meu-nextjs
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    networks:
      - local_network
      
  nginx:
    image: nginx:latest
    container_name: meu-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - strapi
      - minio
      - nextjs
    networks:
      - local_network

networks:
  local_network:
