version: '3.1'
services:
  banco:
    image: postgres:latest
    container_name: meu-postgres-container
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data # Mapeia o diretório de dados do PostgreSQL

  minio:
    image: minio/minio
    container_name: minio
    # hostname: images

    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  strapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - banco
      - minio
    volumes:
      - ./data/strapi:/srv/app

  nextjs:
    build:
      context: ./front # Substitua pelo caminho para o seu código-fonte do Next.js
      dockerfile: Dockerfile
    container_name: meu-nextjs
    ports:
      - "3000:3000"
    depends_on:
      - strapi
