version: '3'
services:
  nextjs:
    build:
      context: ./front
    ports:
      - "3000:3000"
    depends_on:
      - strapi
    command: yarn start  # Comando de inicialização do Next.js usando Yarn

  strapi:
    build:
      context: ./back
    ports:
      - "1337:1337"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: teste
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
    command: yarn start  # Comando de inicialização do Strapi usando Yarn

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
